#! perl

my $bin = (-d '/run/current_system/sw/bin') ? '/run/current-system/sw/bin' : '/usr/bin';

sub on_sel_grab {
    my $query = $_[0]->selection;
    open (my $pipe,"| $bin/xclip -in") or die;
    print $pipe $query;
    close $pipe;
}

sub paste {
    my ($self) = @_;
    my $content = `$bin/xclip -o` ;
    $self->tt_write ($content);
}

sub on_user_command {
    my ($self, $cmd) = @_;
    if ($cmd eq "clipboard:paste") {
        $self->paste;
    }
}
